require:
  - rubocop-slim
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Include:
    - '**/*.rb'
    - '**/*.slim'
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'script/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'

Metrics/AbcSize:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

